### PR TITLE
Update Dockerfile to support custom uid/gid

### PR DESCRIPTION
**Pull request by briantist**
Added optional arguments that can build the image with a custom uid and gid for the `wine:wine` user:group.
This is useful in situations where the wine user needs access to a mounted filesystem without having to modify the host's FS or running as `root` (such as in Jenkins).

### CODE REVIEW

**Comment by briantist** [comment]
@zwass would you consider merging this?
Of all the various WIX containers out there, I found this one very straightforward and small, but I needed this change to be able to use it effectively from a Jenkins pipeline. 

It shouldn't change the container you'd be publishing when built with no params, but for people building locally it helps to be able to just pass in UID/GID.

**Review by zwass — CHANGES_REQUESTED** [review]
I'm happy to merge this. Can you please clean up the indentation? It just looks a little inconsistent.

**Comment by zwass** [comment]
Please rebase as well since I've just made a couple of changes (including a GitHub Actions test for the container build).

**Comment by briantist** [comment]
sure thing, I'll rebase and look at fixing up indentation.
Do you have any opinion on indenting inside the `if`/`fi` blocks?

**Comment by zwass** [comment]
I'm impartial as long as it's consistent. Thanks!

**Comment by briantist** [comment]
I submitted this PR via the editor on GitHub, weirdly when I pulled it down locally the indentation looked consistent in my editor. Changing from tabs to spaces seems to have done the trick.

If you prefer tabs lmk and I'll change them back and get them to align both locally and in the GitHub view.

Also rebased.

**Review by zwass — APPROVED** [review]
Looks great! Thank you.

**Pull request merged**
