### PR TITLE
Bump up alpine, freetype, and wine versions

### PR DESCRIPTION
**Pull request by nvasudevan**
The newer versions seem to work for me, I am able to build MSI's. Thanks.

### CODE REVIEW

**Comment by nvasudevan** [comment]
@zwass If the changes are acceptable, could we get this merged? Thanks.

**Review by zwass — CHANGES_REQUESTED** [review]
The changes to the Dockerfile look good to me, but the .drone.yml is not appropriate to merge into this repo. Maybe that's supposed to be used internally by your organization?

**Comment by nvasudevan** [comment]
> The changes to the Dockerfile look good to me, but the .drone.yml is not appropriate to merge into this repo. Maybe that's supposed to be used internally by your organization?

Sorry, fixed now. Thanks for pointing that out. :)

**Review by zwass — APPROVED** [review]
Thanks!

**Pull request merged**
